### ISSUE TITLE
I'm trying to load incentives but its aborting subgraph instance at staker mappings

### ISSUE THREAD

**Issue by hamzamughal74** [vbstreetz/uniswap-v3-staker-subgraph#1]
![ssss](https://user-images.githubusercontent.com/42102848/176457582-ecba65c6-f475-45d3-8a20-4cfae5b56dd5.png)

on the following line 21
![image](https://user-images.githubusercontent.com/42102848/176457845-73a05b5f-e302-40d2-b228-bfd87a27a411.png)

**Comment by kelonye** [comment]
Hey! Whats the subgraph deployment id? But looks like its happening on line 21 ... probably cus of one of the values in the turple.

**Comment by hamzamughal74** [comment]
Link to subgraph :  https://thegraph.com/hosted-service/subgraph/hamzamughal74/uniswap-incentive?selected=logs

here's deployment id 

QmYBeNg98MhRSe6d7kv8fLcFiVjRM84tDhJLR4v43cK1EF

**Comment by kelonye** [comment]
Added a comment here https://github.com/hamzamughal74/staker-rinkeby/commit/341effcd18e0b2a67f28d71d6c11a5a4aa799e1a

**Comment by hamzamughal74** [comment]
https://thegraph.com/docs/en/developer/assemblyscript-migration-guide/#casting

according to this i have changed api version to 0.0.6 and graph-cli and graph-ts versions to latest
and for upcasting new method is introduced in this guide instead of ethereum.Value.fromTuple(**incentiveIdTuple as ethereum.Tuple**)
can you help me what i need to change here  for upcasting?

**Comment by kelonye** [comment]
gotcha. try this we see:

ethereum.Value.fromTuple(changetype<ethereum.Tuple>(incentiveIdTuple))

**Comment by hamzamughal74** [comment]
in nft position manager handleTransfer 
export function handleTransfer(event: Transfer): void {
  let entity = Position.load(event.params.tokenId.toHex());
  if (entity != null) {
    entity.oldOwner = event.params.to;
    entity.owner = event.params.from;
    entity.approved = null;
    entity.save();
  }
}
it it right? i think entity.oldOwner should be event.para.from and entity.owner = event.params.to?

**Comment by hamzamughal74** [comment]
yes it worked like charm!
