### ISSUE TITLE
need to fix handleTransfer in nft position manager

### ISSUE THREAD

**Issue by hamzamughal74** [vbstreetz/uniswap-v3-staker-subgraph#2]
```
export function handleTransfer(event: Transfer): void {
  let entity = Position.load(event.params.tokenId.toHex());
  if (entity != null) {
    entity.oldOwner = event.params.to;
    entity.owner = event.params.from;
    entity.approved = null;
    entity.save();
  }
}
```
i think it should be this way 
```
entity.oldOwner = event.params.from ;
entity.owner = event.params.to;
```

what you say?

**Comment by kelonye** [comment]
gotcha. please create a PR for the fix...

**Comment by kelonye** [comment]
ok pushed the quickfix :)

**Comment by kelonye** [comment]
btw, seems there's a new version ... not sure if it impacts the subgraph https://github.com/Uniswap/v3-staker

**Comment by hamzamughal74** [comment]
> 



> btw, seems there's a new version ... not sure if it impacts the subgraph https://github.com/Uniswap/v3-staker

yea i'm using this subgraph with new version  v3-staker and it's working perfect

add me on discord => mhamzza#3892

**Comment by hamzamughal74** [comment]
and please let me know if we have any JS version of frontend ?

**Comment by kelonye** [comment]
gotcha. do you mean this https://github.com/vbstreetz/uniswap-v3-staker-frontend?

**Comment by hamzamughal74** [comment]
> 

yes this is typscript i need js version

**Comment by kelonye** [comment]
> > 
> 
> yes this is typscript i need js version

gotcha. time to learn typescript then :)

**Comment by hamzamughal74** [comment]
i have two quick questions

1. i wanna know what  reward:time  ratio is being distributed and do it consider postion size?
2. is there any way i could get realtime data of rewards? because every time i change incentive from select list it updates   ?

**Comment by kelonye** [comment]
> i have two quick questions
> 
> 1. i wanna know what  reward:time  ratio is being distributed and do it consider postion size?
> 2. is there any way i could get realtime data of rewards? because every time i change incentive from select list it updates   ?

1. The rate is not static because it decreases as more users enter the pool. As for the current rate/apr. You can probably calculate:
```
apr = current incentive accured rewards * incentive duration / time elapased
```
see below on how to get the accrued rewards of a particular incentive

2. We noticed during the development of the frontend that it is only possible to compute the rewards per incentive and not per position.  See https://github.com/vbstreetz/uniswap-v3-staker-frontend/blob/main/src/pages/Positions.tsx#L265-L268

sorry, was a really longtime working on this :)
